name: MangoQuest
main: me.Cutiemango.MangoQuest.Main
version: 1.0.0
authors: [Cutiemango]
depend: [Vault, Citizens]
commands:
   mq:
      description: Main command for MangoQuest
   mqe:
      description: MangoQuest Editor Comamnd