name: MangoQuest
main: me.Cutiemango.MangoQuest.Main
version: {$VERSION}
authors: [Cutiemango, 坏黑]
depend: [Vault, Citizens, TabooLib]
commands:
   mq:
      description: Main command for MangoQuest
   mqa:
      description: Admin command for MangoQuest