name: MangoQuest
main: me.Cutiemango.MangoQuest.Main
version: 1.7.7
authors: [Cutiemango]
depend: [Vault, Citizens]
commands:
   mq:
      description: Main command for MangoQuest
   mqa:
      description: Admin command for MangoQuest